name: yamllit execution workflow

on:
  workflow_call:
    inputs:
      distro:
        description: 'Docker container distribution name'
        default: 'centos7'
        type: string
      molecule-scenario:
        description: 'Molecule scenario name.'
        default: 'default'
        type: string

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.9

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python3 -m pip install -r molecule/requirements.txt

      - name: Test with molecule
        run: |
          molecule test --scenario-name ${{ inputs.molecule-scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ inputs.distro }}
          MOLECULE_NO_LOG: False
          PROFILE_TASKS_SORT_ORDER: 'none'
          PROFILE_TASKS_TASK_OUTPUT_LIMIT: '100'
          PY_COLORS: '1'
          TZ: 'Asia/Tokyo'

      - name: Show Ansible version
        run: |
          pip list | grep ansible \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
          ansible --version

      - name: Show molecule version
        run: |
          molecule --version
        env:
          PY_COLORS: '1'
