name: Ansible Molecule execution workflow

on:
  workflow_call:
    inputs:
      artifacts-file-name:
        description: 'Workflow artifacts file name'
        default: ''
        type: string
      artifacts-file-path:
        description: 'Workflow artifacts file path'
        default: ''
        type: string
      molecule-image:
        description: 'Molecule image. ex:centos:7,public.ecr.aws/owner/image:tag,ghcr.io/org/repo/image:tag'
        default: 'centos:7'
        type: string
      molecule-scenario:
        description: 'Molecule scenario name.'
        default: 'default'
        type: string
      pip-requirements-file:
        description: 'Path of Pip requirements file'
        default: 'molecule/requirements.txt'
        type: string
      python-version:
        description: 'Python version'
        default: 3
        type: string

jobs:
  molecule:
    runs-on: ubuntu-latest

    steps:
      - name: Disable mysqld AppArmor
        run: |
          sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ inputs.python-version }}"

      - name: Install Pip requirements
        run: |
          pip install -r ${{ inputs.pip-requirements-file }}

      - name: Test with molecule
        run: |
          molecule test --scenario-name ${{ inputs.molecule-scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_IMAGE: ${{ inputs.molecule-image }}
          MOLECULE_NO_LOG: False
          PROFILE_TASKS_SORT_ORDER: 'none'
          PROFILE_TASKS_TASK_OUTPUT_LIMIT: '100'
          PY_COLORS: '1'
          TZ: 'Asia/Tokyo'

      - name: Upload workflow artifacts
        if: ${{ inputs.artifacts-file-path }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifacts-file-name }}
          path: ${{ inputs.artifacts-file-path }}

      - name: Show Ansible version
        run: |
          pip list | grep ansible \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
          ansible --version

      - name: Show molecule version
        run: |
          molecule --version
        env:
          PY_COLORS: '1'
